version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=skillz
      - MYSQL_USER=skillz
      - MYSQL_PASSWORD=skillz
    ports:
      - 3306:3306
    networks:
      - backend

  back:
    image: eu.gcr.io/wescale-site/xebiafrance/skillz-back:0.0.19
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    networks:
      - backend
    environment:
        - RDS_HOST=db
        - RDS_USER=skillz 
        - RDS_PORT=3306
        - RDS_DATABASE=skillz 
        - RDS_PASSWORD=skillz

  web:
    image: eu.gcr.io/wescale-site/xebiafrance/skillz-front:0.0.14
    links:
       - back
    depends_on:
      - back
    ports:
      - 80:80
    networks:
      - backend
    environment:
      - API_URL="http://localhost:8080/api/v1"
      - PORT=80
      - NODE_ENV=production

networks:
  backend:
