version: "3"

services:
  loadbalancer:
    image: traefik
    command: --web --docker --logLevel=DEBUG
    networks:
      - backend
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=skillz
      - MYSQL_USER=skillz
      - MYSQL_PASSWORD=skillz
    ports:
      - 3306:3306
    networks:
      - backend

  back:
    image: skillz/back:latest
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
    environment:
      - RDS_HOST=db
      - RDS_USER=skillz 
      - RDS_PORT=3306
      - RDS_DATABASE=skillz 
      - RDS_PASSWORD=skillz
    expose:
      - 8080
    labels:
      - "traefik.backend=back"
      - "traefik.frontend.rule=Host:skillz-back"

  dbmigrate:
    image: skillz/dbmigrate:latest
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
    environment:
        - RDS_HOST=db
        - RDS_USER=skillz 
        - RDS_PORT=3306
        - RDS_DATABASE=skillz 
        - RDS_PASSWORD=skillz

  web:
    image: skillz/front:latest
    networks:
      - backend
    environment:
      - API_URL="http://skillz-back:80/api/v1"
      - PORT=80
      - NODE_ENV=production
    expose:
      - 80
    labels:
      - "traefik.backend=front"
      - "traefik.frontend.rule=Host:skillz-front"

networks:
  backend:
