apiVersion: v1
kind: Service
metadata:
  name: back-svc
  namespace: skillz
  labels:
    app: skillz
spec:
  ports:
    - port: 8080
      nodePort: 32000
  selector:
    app: skillz
    tier: back
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: skillz-back-deployment
  namespace: skillz
  labels:
    app: skillz
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: skillz
        tier: back
    spec:
      containers:
      - image: eu.gcr.io/wescale-site/xebiafrance/skillz-back:0.0.19
        name: skillz-back
        env:
        - name: RDS_HOST
          value: skillz-db-mysql
        - name: RDS_USER
          value: skillzdbuser 
        - name: RDS_PORT
          value: "3306"
        - name: RDS_DATABASE
          value: skillz 
        - name: RDS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: skillz-db-mysql
              key: mysql-password
        ports:
        - containerPort: 8080
          name: skillz-back 

