apiVersion: v1
kind: PersistentVolume
metadata:
  name: skillz-pv-1
  namespace: skillz
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: skillz-1
    fsType: ext4
